node:
  build: .
  command: npm run watch
  environment:
    APP_PORT: 17461
    APP_ENDPOINT: https://membres.openfab.be
    EMAIL_API_KEY: ${EMAIL_API_KEY}
    EMAIL_DOMAIN: ${EMAIL_DOMAIN}
    EMAIL_FROM: 'Openfab <postmaster@sandbox381251d0eb4544a883475a5bff3928fe.mailgun.org>'
    EMAIL_TO: 'louis@openfab.be'
    LOG_LEVEL: debug
    NODE_ENV: development
    PG_HOST: postgresql
    PG_USER: postgres
    PG_DB: postgres
    SECURITY_HASH_SALT: openfabiswatchingus
    SECURITY_SECRET: openfabiswatchingus
  ports:
    - "19461:17461"
  volumes:
    - ./config:/var/www/config
    - ./src:/var/www/src
    - ./package.json:/var/www/package.json
  links:
    - postgresql

postgresql:
  image: postgres:9.5
  ports:
    - "5460:5432"
